projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: nh7nhovtynh6zcv6unl34xzodi
        frontend: javascript
        framework: react
        maxDepth: 2
